---
  output:
  pdf_document: default
html_document: default
---
  
  #################################################

#  University     : Stevens Institute of Technology
#  Project        : HW_03 KNN 
#  Purpose        : Homework
#  First Name     : Omkar
#  Last Name      : Sinha
#  CWId			      : 10468312
#  Date           : 10/17/2021
#  Comments       : Kindly knit in PDF format


#################################################  


\    
\

```{r}

##Uploading the file, omitting the missing value rows and converting labels to factor Class

rm(list=ls())

BCW = read.csv("C:/breast-cancer-wisconsin.data.csv",header = TRUE, sep = ",",na.strings = c("?"))

#Remove the rows with missing values 
BCW <- na.omit(BCW)

#Convert labels to factor class
BCW$Class <- factor(BCW$Class,levels = c("2","4"),labels = c("Benign","Malignant"))

```

\
\

## K-nearest Neighbors (KNN)


\ 

```{r}

#Generating train and test data in the ratio of 70:30

size   <- sample(1:nrow(BCW),0.7*nrow(BCW)) 
norm1  <- function(x) {(x -min(x))/(max(x)-min(x))}


##Executing normalization on first 4 columns of the given data because they are the predictors
norm2 <- as.data.frame(lapply(BCW[,c(2,3,4,5,6,7,8,9,10)],norm1))
BCW2  = BCW['Class']

#Train set
train_size <- norm2[size,] 
cl_train   <- BCW2[size,]

##Test set
test_size <- norm2[-size,] 
cl_test   <- BCW2[-size,]

#Loading the package class
library(class)

#Running KNN for k = 3
clf <- knn(train_size,test_size,cl=cl_train,k=3)

#Creating confusion matrix
conf_matrix <- table(clf,cl_test)
print(conf_matrix)

#Accuracy
accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
accuracy(conf_matrix)

#Running KNN for k = 5
clf <- knn(train_size,test_size,cl=cl_train,k=5)

#Creating confusion matrix
conf_matrix <- table(clf,cl_test)
print(conf_matrix)

#Accuracy
accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
accuracy(conf_matrix)

#Running KNN for k = 10
clf <- knn(train_size,test_size,cl=cl_train,k=5)

#Creating confusion matrix
conf_matrix <- table(clf,cl_test)
print(conf_matrix)

#Accuracy
accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
accuracy(conf_matrix)

```

\ 
\ 
\ 

# End of Assignment 3 - KNN
